const express = require("express");
const mongoconnect = require("./config/db");
const morgan = require("morgan");
const authroutes = require("./routes/authroutes");
const app = express();
var cors = require("cors");
const productroute = require("./routes/Productroutes");
const path = require("path");
app.use(cors());
app.use(express.json());
app.use(morgan("dev"));
require("dotenv").config();
app.use(express.static(path.join(__dirname, "./client/build")));
mongoconnect();
const PORT = process.env.PORT || 8080;
app.use("*", function (req, res) {
  res.sendFile(path.join(__dirname, "./client/build/index.html"));
});
app.post("/api/createuser", authroutes);
app.post("/api/login", authroutes);
app.get("/test", authroutes);
app.get("/api/user-auth", authroutes);
app.post("/api/forgotpassword", authroutes);
app.post("/api/admin-auth", authroutes);
app.post("/api/createcategory", authroutes);
app.get("/api/getcategory", authroutes);
app.put("/api/updatecategory/:id", authroutes);
app.delete("/api/deletecategory/:id/:useremail", authroutes);
app.get("/api/single-category/:slug", authroutes);
app.post("/api/createproduct", productroute);
app.get("/api/getproduct", productroute);
app.get("/api/getproduct/:slug", productroute);
app.get("/api/product-photo/:pid", productroute);
app.delete("/api/product/:pid/:useremail", productroute);
app.put("/api/updateproduct/:pid", productroute);
app.get("/api/search/:keyword", productroute);
app.get("/api/braintree/token", productroute);
app.post("/api/braintree/payment", productroute);
app.get("/api/getorders/:id", productroute);
app.post("/api/getallorders/:id", productroute);
app.put("/api/updatprofile", authroutes);
app.listen(PORT, () => {
  console.log(`Server is Listening On PORT ${PORT}`);
});
